### PR TITLE
Development

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/panelapp_api/9)

### CODE REVIEW

**Comment by aledj2** [comment]
This will need to be changed to the production db before used

**Comment by andyb3** [comment]
+@andyb3 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-:-L3TIXpNl1fMgi-969Ee:bxccsfn)*

**Comment by andyb3** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[insert_to_moka.py, line 31 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TUMBYpv7j2UExxXA8:-L3TUMBYpv7j2UExxXA9:b-glvvmu) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L31)):*
> ```Python
>         # the file containing the result of the API query
>         self.API_result = "F:\\Moka\\Files\\Software\\PanelApp\\20180118_PanelAppOut_modified.txt"
>         self.API_symbol_result = "F:\\Moka\\Files\\Software\\PanelApp\\20180118_PanelAppOut_symbols.txt"
> ```

Is it worth changing these to UNC filepaths in case script is run from a PC where F:\ isn't mapped?

---

*[insert_to_moka.py, line 39 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TVP0Cw21p_RfhWZbc:-L3TVP0Cw21p_RfhWZbd:byrv75c) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L39)):*
> ```Python
> 
>         # variables for the database connection
>         self.cnxn = pyodbc.connect("DRIVER={SQL Server}; SERVER=GSTTV-MOKA; DATABASE=devdatabase;")
> ```

Does this need to be changed from devdatabase to mokadata?

---

*[insert_to_moka.py, line 121 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TW0LggwzXwZXm8ZVp:-L3TW0LggwzXwZXm8ZVq:b-f8hrei) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L121)):*
> ```Python
>         
>         # split to capture the version number
>         for i in self.API_list:
> ```

Maybe change `i` to more descriptive variable name?

---

*[insert_to_moka.py, line 151 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TWn1cD9lgT7WdxGat:-L3TWn1cD9lgT7WdxGau:b2j6iyc) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L151)):*
> ```Python
>         
>         #loop through results and append to a list
>         for i in list_of_db_versions:
> ```

Could you change `i` to a more descriptive name, and say in the comments what it looks like (e.g. why are you taking the first element on line below?)

---

*[insert_to_moka.py, line 195 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TYdr_HugFfhjw_Zs8:-L3TYdr_HugFfhjw_Zs9:b-nds5cy) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L195)):*
> ```Python
>         
>         #loop through and extract required info
>         for i in self.API_list:
> ```

Could `i` be changed to more descriptive name?

---

*[insert_to_moka.py, line 227 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TZJBCbiYJz5YX3_F1:-L3TZJBCbiYJz5YX3_F2:bnjx54b) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L227)):*
> ```Python
>             # if panel not in items table already insert it
>             else:
>                 #print "New panel: %s. inserting to item table" % self.panel_name_colour
> ```

Can this print statement be removed?

---

*[insert_to_moka.py, line 258 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3T_1xt4MsvHSV0xQpq:-L3T_1xt4MsvHSV0xQpr:b-8yhro6) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L258)):*
> ```Python
>                     # else this version number is lower than a previously seen version
>                     else:
>                         pass
> ```

Do you need an `else: pass` here? If neither the `if` or `elif` conditions were met it wouldn't it just pass to the next record anyway?

---

*[insert_to_moka.py, line 290 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TbHXMWu4YBAmDhBBc:-L3TbHXMWu4YBAmDhBBd:bsvgatu) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L290)):*
> ```Python
>             # if not a new version ignore
>             else:
>                 #print "no update to %s " % self.panel_name_colour 
> ```

Can this print statement be removed? Is this `else: pass` clause necessary?

---

*[insert_to_moka.py, line 300 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3Tbe6-v8Ke4we-hM6r:-L3Tbe6-v8Ke4we-hM6s:b-aihs0q) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L300)):*
> ```Python
>         # convert the string containing gene list into a python list
>         # split and remove all unwanted characters
>         for i in list_of_genes.split(","):
> ```

Could `i` be changed to more descriptive variable name?

---

*[insert_to_moka.py, line 306 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TcX126QyRhfrGVhVj:-L3TcX126QyRhfrGVhVk:bqyygw1) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L306)):*
> ```Python
> 
>         #loop through gene list
>         for ensbl_id in list_of_genes_cleaned:
> ```

Are the pass statements in this for loop necessary?

---

*[insert_to_moka.py, line 332 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3Tcj9ItMVauLw-fOhy:-L3Tcj9ItMVauLw-fOhz:b-dqiuwf) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L332)):*
> ```Python
>         self.ignore=False
>         
>         # Call module to insert any gene symbols which do not have an emsembl if in panel app, or in the HGNC_translation table.
> ```

Should this say ensembl id?

---

*[insert_to_moka.py, line 347 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3Td5rnCyVrMEvR8_wp:-L3Td5rnCyVrMEvR8_wq:btd3xq4) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L347)):*
> ```Python
>         db_list = []
>         # lop through the select query reponse
>         for i in imported_genes:
> ```

could `i` be a more descriptive name? 

---

*[insert_to_moka.py, line 402 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TdjZ5Ee2szjWX7Lc8:-L3TdjZ5Ee2szjWX7Lc9:b8jm3f) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L402)):*
> ```Python
>                 panel_hash_colour = panel_hash + "_" + colour
>                 #rebuild the panelapp name
>                 panel_name_colour=panel_name+" (Panel App "+colour+" v"+str(version)+")"
> ```

Could you add whitespace around operators

---

*[ReadPanelApp.py, line 44 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TShZvfXYhUuoH9fLL:-L3TShZvfXYhUuoH9fLM:bkrybzj) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/ReadPanelApp.py#L44)):*
> ```Python
>             # create a tuple of the name and version
>             # replace underscore from panel names to prevent issues splitting this string when importing to moka
>             toople = (str(panel["Panel_Id"]),str(panel["Name"].replace("_","-")), str(panel["CurrentVersion"]))
> ```

Add space after comma between first and second element of tuple 

---

*[ReadPanelApp.py, line 45 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TQ79e6RfmMEKE-BGc:-L3TQ79e6RfmMEKE-BGd:bnjx54b) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/ReadPanelApp.py#L45)):*
> ```Python
>             # replace underscore from panel names to prevent issues splitting this string when importing to moka
>             toople = (str(panel["Panel_Id"]),str(panel["Name"].replace("_","-")), str(panel["CurrentVersion"]))
>             #print toople
> ```

Can this print statement be removed?

---

*[ReadPanelApp.py, line 56 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TRWmX1BuT7TFIszNC:-L3TRWmX1BuT7TFIszND:b-5c0rkp) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/ReadPanelApp.py#L56)):*
> ```Python
>         '''This module loops through each panel and retrieves the genes within this panel as a json'''
>         # loop through dict
>         for i in self.dict_of_panels:
> ```

Could `i` be changed to a more descriptive variable name?

---

*[ReadPanelApp.py, line 114 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TSDwjUsJK5swn2GMn:-L3TSDwjUsJK5swn2GMo:b-qqha7b) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/ReadPanelApp.py#L114)):*
> ```Python
>         #open two files, one to capture all ensembl ids for each panel and one to capture a list of symbols.
>         outputfile=open(self.outputfilepath + self.now + "_PanelAppOut.txt",'w')
>         symbols_outputfile=open(self.outputfilepath + self.now + "_PanelAppOut_symbols.txt",'w')
> ```

Add a whitespace either side of `=` in variable assignments, and after comma before `'w'`

---

*[ReadPanelApp.py, line 116 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TSBowtU1xdqTQ67Ij:-L3TSBowtU1xdqTQ67Ik:b-5c0rkp) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/ReadPanelApp.py#L116)):*
> ```Python
>         symbols_outputfile=open(self.outputfilepath + self.now + "_PanelAppOut_symbols.txt",'w')
>         # for each panel
>         for i in self.dict_of_panels:
> ```

Could `i` be changed to a more descriptive variable name?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9)*

**Comment by andyb3** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[insert_to_moka.py, line 39 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TVP0Cw21p_RfhWZbc:-L3X7yBIBttDws6erBsH:b9vcgcv) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L39)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Does this need to be changed from devdatabase to mokadata?
</blockquote></details>

Sorry just saw your comment about this on the PR. Ignore!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9)*

**Comment by aledj2** [comment]
Review status: 1 of 3 files reviewed at latest revision, 18 unresolved discussions.

---

*[insert_to_moka.py, line 31 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TUMBYpv7j2UExxXA8:-L3TfetmDubzrALMhFbN:b-896fix) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L31)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Is it worth changing these to UNC filepaths in case script is run from a PC where F:\ isn't mapped?
</blockquote></details>

Done.

---

*[insert_to_moka.py, line 121 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TW0LggwzXwZXm8ZVp:-L3TfqAGRaHcKLCMrqn5:b-896fix) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L121)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Maybe change `i` to more descriptive variable name?
</blockquote></details>

Done.

---

*[insert_to_moka.py, line 151 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TWn1cD9lgT7WdxGat:-L3TgG0t-c4kNVQ3x3X4:b-896fix) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L151)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Could you change `i` to a more descriptive name, and say in the comments what it looks like (e.g. why are you taking the first element on line below?)
</blockquote></details>

Done.

---

*[insert_to_moka.py, line 195 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TYdr_HugFfhjw_Zs8:-L3TgUaDefdftTVyvj7I:b-896fix) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L195)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Could `i` be changed to more descriptive name?
</blockquote></details>

Done.

---

*[insert_to_moka.py, line 227 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TZJBCbiYJz5YX3_F1:-L3TgZ95H0kJxRBFuykN:b-896fix) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L227)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Can this print statement be removed?
</blockquote></details>

Done.

---

*[insert_to_moka.py, line 258 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3T_1xt4MsvHSV0xQpq:-L3Tge_dnCN0s7mC81aA:b-mwat83) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L258)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Do you need an `else: pass` here? If neither the `if` or `elif` conditions were met it wouldn't it just pass to the next record anyway?
</blockquote></details>

have left this in purely to help follow what is happening

---

*[insert_to_moka.py, line 290 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TbHXMWu4YBAmDhBBc:-L3Tgrt77T_so_m334xp:b-4nt4ct) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L290)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Can this print statement be removed? Is this `else: pass` clause necessary?
</blockquote></details>

again, have left in purely for documentation

---

*[insert_to_moka.py, line 300 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3Tbe6-v8Ke4we-hM6r:-L3Th22xJHyUzSmReVF0:b-896fix) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L300)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Could `i` be changed to more descriptive variable name?
</blockquote></details>

Done.

---

*[insert_to_moka.py, line 306 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TcX126QyRhfrGVhVj:-L3ThCrrTlyGeLFkZSt3:bh789xw) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L306)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Are the pass statements in this for loop necessary?
</blockquote></details>

have removed one, the second is needed to stop trying to split something which shouldn't be split

---

*[insert_to_moka.py, line 332 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3Tcj9ItMVauLw-fOhy:-L3ThR5o5w9-8X43AEKO:b-896fix) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L332)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Should this say ensembl id?
</blockquote></details>

Done.

---

*[insert_to_moka.py, line 347 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3Td5rnCyVrMEvR8_wp:-L3ThXjovUSQmK_KV8G_:b-896fix) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L347)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

could `i` be a more descriptive name? 
</blockquote></details>

Done.

---

*[insert_to_moka.py, line 402 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TdjZ5Ee2szjWX7Lc8:-L3ThhB9kRKwY7AYFtnq:b-896fix) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/insert_to_moka.py#L402)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Could you add whitespace around operators
</blockquote></details>

Done.

---

*[ReadPanelApp.py, line 44 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TShZvfXYhUuoH9fLL:-L3Ti4FeUVqxltZpzh7L:b-896fix) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/ReadPanelApp.py#L44)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Add space after comma between first and second element of tuple 
</blockquote></details>

Done.

---

*[ReadPanelApp.py, line 45 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TQ79e6RfmMEKE-BGc:-L3Ti7s1fMwZUCFDGlfF:b-896fix) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/ReadPanelApp.py#L45)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Can this print statement be removed?
</blockquote></details>

Done.

---

*[ReadPanelApp.py, line 56 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TRWmX1BuT7TFIszNC:-L3TiNVeqiQcsp9UaGOH:b-896fix) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/ReadPanelApp.py#L56)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Could `i` be changed to a more descriptive variable name?
</blockquote></details>

Done.

---

*[ReadPanelApp.py, line 114 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TSDwjUsJK5swn2GMn:-L3TiTdt43pOp6h3HyqN:b-896fix) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/ReadPanelApp.py#L114)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Add a whitespace either side of `=` in variable assignments, and after comma before `'w'`
</blockquote></details>

Done.

---

*[ReadPanelApp.py, line 116 at r1](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-L3TSBowtU1xdqTQ67Ij:-L3XgEKhR8bNjIqlkje_:b-896fix) ([raw file](https://github.com/moka-guys/panelapp_api/blob/e9020955ba5c91ebb68ae044777a335cf987544b/ReadPanelApp.py#L116)):*
<details><summary><i>Previously, andyb3 wrote…</i></summary><blockquote>

Could `i` be changed to a more descriptive variable name?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9)*

**Comment by andyb3** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/moka-guys/panelapp_api/9#-:-L3XmDVOrSe9gQxCljvg:bnfp4nl)*

**Pull request merged**
